### PR TITLE
Added dark/light mode

### PR DESCRIPTION
**Pull request by abitsalihu**
Added a button which will let the user go between `dark` and `light` mode on `click`.

Below is a video of how the button will work:

https://user-images.githubusercontent.com/94648837/192115102-e1feb861-1b30-4563-8175-a7e6d5fd8777.mov

### CODE REVIEW

**Comment by abitsalihu** [comment]
@jeffreycharters I'm sorry I didn't do a pull request before pushing my changes. I did not know someone else pushed something. 😕

**Comment by jeffreycharters** [comment]
It's all good, this will give me a chance to go through and make sure I can only change the code that we want changed. I'm learning too. I might not have a chance to look through this until tomorrow.

**Comment by abitsalihu** [comment]
@jeffreycharters Alright, I was thinking of adding a function tomorrow to make it easier to understand and easier on the js script as it would have less code.

**Comment by jeffreycharters** [comment]
Sure - so I'll wait for you to push more changes unless you change your mind and let me know.

**Comment by abitsalihu** [comment]
@jeffreycharters I'll push the changes on this one tomorrow and then u can just resolve the latest changes tomorrow on this one.

**Comment by sarajw** [comment]
Oooh this is a chewy one. Yeah as it stands, the site was just responding to the user's light or dark mode with color-scheme - these seem to be co-existing together! I'll have a closer look tomorrow

**Comment by abitsalihu** [comment]
You guys can go ahead and review the code as it is, I was not able to refactor the stuff that I wanted. :)

**Review by jeffreycharters — APPROVED** [review]

**Comment by jeffreycharters** [comment]
Sorry it took so long, got busy doing real-life stuff. Thanks for doing this @abitsalihu, feel free to work away at it in the future if you feel like it.

**Comment by abitsalihu** [comment]
@jeffreycharters thanks for letting me. :)

**Pull request merged**
