### PR TITLE
Fixed bulletpoints styling of list items.

### PR DESCRIPTION
**Pull request by publikphigor**
### Before
Screenshot from 2022-10-04 12-32-44

### After
Screenshot from 2022-10-04 12-32-57

### CODE REVIEW

**Review by michaella23 — CHANGES_REQUESTED** [review]
Hello! This was listed as an issue and had been assigned to someone, but a few different people attempted to resolve it. Will you pull the upstream branch and resolve any conflicts please? I think that the styling still needs a little bit of help. Thanks for your contribution!

**Comment by publikphigor** [comment]
Sorry for causing confusion. I forked and worked on what I saw.

I didn't know it was already an open issue.
Do I wait for the assignees PR to be merged or work on something else?

**Comment by michaella23** [comment]
hey @publikphigor it's no problem! the other PRs have already been merged, so you can pull down the upstream branch and compare yours to resolve conflicts. if there are any more changes you think need to be made on this element, go ahead!

**Comment by publikphigor** [comment]
Will do that. Thank you 👍🏿

**Comment by publikphigor** [comment]
I have pulled the upstream and resolved merge conflicts. The list items are fixed now.

**Review by michaella23 — APPROVED** [review]
Thank you!

**Pull request merged**
