### PR TITLE
[docs]: added license, resolves #65

### LINKED ISSUE #65: [DOCS]: add a license
Hey, I looked at the project and it has no license which tells contributors and others who may want to use the project what levels of access they can have. I propose to give the project either an MIT license or an Apache one, and can I work on adding it?

N.B: licenses are good to show the level of open source-ness of a project

### PR DESCRIPTION
**Pull request by akebu6**
Resolves #65   
Created an MIT license for Station to show the open source-ness of the project which allows contributors to know what kind of rights they have when using the project

### CODE REVIEW

**Review by jeffreycharters — APPROVED** [review]

**Comment by jeffreycharters** [comment]
Looks good, I hadn't actually thought of adding a licence but it is probably good to be explicit about it being open source. Thanks!

**Comment by akebu6** [comment]
Yes, when it's explicit it means that even contributors know it's open source or not depending on the license that it has. It's one of the things I got to learn thanks to Eddie Jaoude

**Comment by jeffreycharters** [comment]
I hadn't heard of Eddie but I looked him up and seems to be a smart guy! Thanks for the tip.

**Comment by akebu6** [comment]
It's my pleasure!

**Pull request merged**
