### PR TITLE
Change list style

### PR DESCRIPTION
**Pull request by RohitRajvaidya5**
PR for Fix the junkiness in the list section #34
Modify index.html and style.css to change the list style .

### CODE REVIEW

**Comment by RohitRajvaidya5** [comment]
If this pull request is right, can you merge it in October, I am a first-time participant in Hacktoberfest 2022

**Comment by jeffreycharters** [comment]
Good stuff, I'll come back and have a look in October. Happy hacking!

**Comment by omk-coder** [comment]
can i work on this issue.

**Comment by RohitRajvaidya5** [comment]
can you merge it now?

**Pull request merged**
