### PR TITLE
Number of visit counter issue  #15

### PR DESCRIPTION
**Pull request by choco-develop**

### CODE REVIEW

**Comment by jeffreycharters** [comment]
This works well and I'm happy with it! Nice work 🥳  But since you seem keen on learning, I'll ask you to change one thing.

In `script.js` you use `window.load`. Instead of this, look into adding an event listening (`addEventListener`) for `DOMContentLoaded`. It should work the same, but notice when the page loads it's blank for a split second before the javascript brings up the text in your div? Hopefully it will get rid of that.

Here is the [MDN documentation on DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event) to get you started. If you don't feel like doing this extra step and I'm happy to approve this Pull Request as it is.

**Comment by choco-develop** [comment]
Oh...thanks a lot for the resource I will go through and make necessary changes..my goal is to be a better developer through open source 
I am happy I am learning new things daily

**Comment by choco-develop** [comment]
I have made the commit.I see the difference between window.load and window.event using DOMContent.😊

**Review by jeffreycharters — APPROVED** [review]

**Comment by jeffreycharters** [comment]
Glad I could help, in most cases DOMContentLoaded is the better option. Sounds like you are doing the same as me, I might just be a bit further along on the journey. Good luck!

**Comment by choco-develop** [comment]
It's nice working on this project with you.🤝
Let's get more issues

**Pull request merged**
