### PR TITLE
Add linear gradient animation to the h2

### PR DESCRIPTION
**Pull request by abitsalihu**
Hey, I added an infinite animation on the h2 title that runs infinitely when the page loads.

Below is a video of how the animation works:

https://user-images.githubusercontent.com/94648837/192091676-672abdc3-e126-474e-8519-ce94415eae33.mov

### CODE REVIEW

**Review by jeffreycharters — APPROVED** [review]

**Comment by jeffreycharters** [comment]
Looks good Abit! My only concern is that when you are viewing the page in light mode, the H2 disappears temporarily when the font colour is white, the same colour as the page background!

Do you have any interest in finding a fix for this? I've approved your Pull Request because it isn't a big deal and I'm glad you've gotten involved :)

**Comment by abitsalihu** [comment]
Hey @jeffreycharters I had not checked it in light mode, my bad. I will check it again and add a feature that when the light mode is active the gradient to be different color, so the starting color will be black.

You can raise an issue and assign me with this.
I'll get into this sometime later today. :)

**Comment by abitsalihu** [comment]
@jeffreycharters I checked the website and I thought u said that there was a light mode, but I checked and there isn't one.
I raised an issue to create a dark/light mode, with a toggle button, and there I can also fix the gradient from changing through modes!

**Comment by jeffreycharters** [comment]
You're not wrong here, in that we don't have a toggle switch - but I think, according to @sarajw, the site will naturally use whatever your system is set to use. But I think adding a toggle is a good idea, thank you for adding the issue!

And there is no rush to any of these things, I'd rather you enjoy the process than feel like you are working on a deadline.

**Pull request merged**
